[package]
name = "java-bindgen"
version = "0.1.0-alpha.1"
edition = "2021"
description = "â˜• + ğŸ¦€ = â¤ï¸â€ğŸ”¥ Java JNI Bindings Generator"
repository = "https://github.com/PawelJastrzebski/java-bindgen"
license = "MIT"
rust-version = "1.70"
keywords = ["java", "jni", "bindings", "jar"]

[dependencies]
jni = { version = "0.21", features = ["invocation"] }
java-bindgen-macro = { path = "./bin/java-bindgen-macro" }